from pydantic import BaseModel, Field, ConfigDict # Import ConfigDict
from typing import List, Optional, Dict, Any, Literal, ClassVar

# NEW: Define research strategies
ResearchStrategy = Literal[
    "research_based",           # Standard research process (search, reflect, etc.)
    "content_based",            # Write based on other sections' content (e.g., intro, conclusion)
    "synthesize_from_subsections" # Synthesize intro from completed subsection research
]

class ReportSection(BaseModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(extra='forbid', json_schema_extra={
        "required": [
            "section_id",
            "title",
            "description",
            "associated_note_ids",
            "subsections",
            "research_strategy"
        ]
    })  # Enforce additionalProperties: false and required fields in schema
    """Defines a section in the final report outline."""
    section_id: str = Field(..., description="Unique identifier for the section (e.g., 'introduction', 'lit_review', 'methodology_results', 'conclusion').")
    title: str = Field(..., description="Human-readable title for the report section.")
    description: str = Field(..., description="Brief description of what this section should cover.")
    associated_note_ids: Optional[List[str]] = Field(default=None, description="List of note IDs from the exploratory phase relevant to this section.") # Added field
    subsections: List['ReportSection'] = Field(default_factory=list, description="List of subsections nested under this section.")
    # --- NEW FIELDS ---
    research_strategy: ResearchStrategy = Field(
        default="research_based",
        description="Defines how the research/writing for this section should be approached."
    )
    # is_section_intro field removed as it's redundant with research_strategy='synthesize_from_subsections'
    # --- END NEW FIELDS ---

# Update forward references to allow for recursive subsections
ReportSection.model_rebuild()

class SimplifiedPlan(BaseModel):
    model_config: ClassVar[ConfigDict] = ConfigDict(extra='forbid')  # Enforce additionalProperties: false in schema
    """Represents the structured research plan and report outline."""
    mission_goal: str = Field(..., description="The overall goal or research question.")
    report_outline: List[ReportSection] = Field(..., description="The planned structure of the final report.")

# Removed SimplifiedPlan model as its fields are now directly in SimplifiedPlanResponse

class SimplifiedPlanResponse(BaseModel):
    """
    The expected JSON structure returned by the Planning Agent LLM call.
    Represents the structured research plan and report outline directly.
    """
    # Add model_config to enforce no extra fields during Pydantic validation
    # AND ensure 'additionalProperties: false' is included in the generated schema.
    model_config: ClassVar[ConfigDict] = ConfigDict(extra='forbid', json_schema_extra={
        "required": [
            "mission_goal",
            "report_outline",
            "parsing_error",
            "generated_thought"
        ]
    })

    mission_goal: str = Field(..., description="The overall goal or research question.")
    report_outline: List[ReportSection] = Field(..., description="The planned structure of the final report.")
    parsing_error: Optional[str] = Field(None, description="Field to indicate if there was an error parsing the LLM response into the schema.")
    generated_thought: Optional[str] = Field(None, description="A concise thought or reminder generated by the agent to be added to the thought_pad.")
